= Managing application endpoints as app provider
:imagesdir: _images/

The developer account offers several functionalities to manage the app providers apps.

== Blocking several or all Instances of Certified Application

The agrirouter provides a mechanism to prevent all or specific instances of an application to send and receive commands. To achieve a blocking of all instances, the agrirouter administrator has the option to change the certification status of an application version from _Approved_ to _Blocked_.

Every app provider can block specific instances of an application in the list of blocked endpoints. This can be used to disallow endpoints to communicate with the agrirouter, e.g. to avoid the app from creating further traffic.

When instances of blocked applications communicate with the agrirouter in order to send or retrieve commands, or to invoke other agrirouter functionalities, the agrirouter will respond with an error message, indicating that the instance is not allowed to use agrirouter functionality because of different reasons (payment not successful, certificate not valid, etc.).

The _Blocking_ status can be changed by the agrirouter administrator to

* _either Approved_ to allow all application instances to communicate again,
* _or to Rejected_ as final status.
