= agrirouter Certification
:imagesdir: _images/
:fn-sdk-relaxed: footnote:sdk-relaxed[This check is obsolete when using one of the official SDKs]

== In General

Every application needs to be certified to communicate with the agrirouter. The certification ensures that the communication protocol of the agrirouter is successfully implemented and the application can communicate correctly with the agrirouter.

A certification is needed any time the application changes its capabilities or their sending directions, changes the commands or uses a different protocol to communicate with the agrirouter.

Also, if core functionality of the agrirouter integration is being reimplemented in the certified product for whatever reason, a re-certification is mandatory.

[IMPORTANT]
=====
Failure to communicate functional changes and re-certify them can lead to temporary deactivation of the application in case of malfunction!
=====

[NOTE]
=====
For a new certification version capabilities can never be removed. Neither can a sending direction of a capability be removed. It is only allowed to add capabilities or sending directions for a new version to ensure downwards compatibility. The capabilities command however can of course only include a subset which is smaller than in the version before.
=====

== Out of focus

The certification will not check if an application is able to work with the data sent over the agrirouter. The process will only check if the application can send and receive data for the technical message types which were selected for the certification version earlier on.

== Certification companies

There are multiple certification companies, a list can be found link:https://my-agrirouter.com/support/certification/[here].

== Certification Requirements

To pass the certification tests there are multiple requirements have to be fulfilled before the certification can start.

=== Prerequisites

* The xref:./partner-process/provider-agreement.adoc[DKE application provider agreement] has to be signed.

* The following information about the company is available:
** Name
** Address (where billing and offer should be placed by the certification company)
* The following first level customer support information is available:
** Mail
** Address
** Phone
** URL
* A xref:./registration.adoc[production environment developer account of the application provider]
* The application Id and certification version Id of xref:./applications.adoc[an application in the production environment].
* Version, name and description of the application to certify.

* Once your certification is approved by the certifier, please send us the SolutionFinder Form xref:./partner-process/solutionfinder.adoc[the Solution-Finder form] so that we can create the entry in the Solution-Finder.

=== Additional requirements during the process

The following information is not required to start the certification but will be required before finishing it:

* Message protocol of the application (MQTT / REST).
* Message format of the application (JSON / Native Protobuf).
* The capabilities of the application including xref:./tmt/overview.adoc[the technical message types] and sending directions.
* A list of xref:./commands/overview.adoc[all commands] that are used by the application.
* Is this an initial certification or a recertification for a new version of an existing software?
* For some test case there has to be at least one extracted original message (as JSON or Base64-Encoded native Protobuf) provided to the certification company.

=== Relaxed requirements when using SDKs

When using one of the official SDKs for the implementation, some requirements will be assumed ok without explicit checks.
These requirements are annotated with {fn-sdk-relaxed} below.

To apply this relaxation, you are required to use the most up-to-date release of the respective SDK!

== Certification timeout

Once the certification is started, it needs to be successfully passed within 10 weeks. Otherwise, additional costs could be incurred. It is important to respect this time range as part of the implementation planning. 


== Certification tests
Not all of the certification tests are necessary for your implementation. The certification company is able to tell you which of the tests are necessary to full fill all requirements.

[NOTE]
====
The term __"All TMTs"__ on this page means "All Technical Message Types that were reported in the application certification version".
====

The selection depends on several parameters and attributes of the specific application. These parameters are listed in the following chapters

=== Based on the application type

Based on the type of your application, different tests are required. Check xref:./applications.adoc[here], which type of application suites your requirements best.

[cols="1,2,4",options="header",]
|====
|Message type |Major for |Expected results / Acceptance criteria

|xref:./integration/onboarding.adoc#onboarding-request[Onboarding]
| CUs
a|
* A new endpoint is visible in the certification account.
* The external Id is a valid URN, see xref:./integration/general-conventions.adoc[general requirements].
* The following application information is visible in the agrirouter UI:
** The application name
** The application manufacturer
** A valid support URL is available
** By clicking on the support URL the following information is available:
*** Mail
*** Address
*** Phone number
* After an endpoint was deleted by the user, a new onboarding has to be possible.
* In case of any error during the onboarding (with the same (re-onboarding) or a different external Id (new onboarding)):
** An error message is shown to the user (**Remark:** During onboarding, there is always a UI available).
** The error message includes the error code returned from agrirouter.
** The error code does not simply copy the error message from agrirouter.
** Error codes that might not yet be documented have to be displayed as well.
* After onboarding, the time of certificate expiration needs to be visible to the user (might be hidden in an "advanced" view or similar)

|xref:./integration/authorization.adoc[Authorization]
|Telemetry platform

Farming software
a|
* After clicking the "Connect"-Button, the success of the onboarding should be shown to the user; e.g. by displaying a website or updating the own UI.
* After clicking the "Reject"-Button, the failure to onboard should be shown to the user.
** The notification should indicate that the onboarding was rejected.

|xref:./integration/onboarding.adoc#verification-request[Verification (optional, if supported)]
|Telemetry platform

Farming software
a|
* After clicking the "Connect"-Button, the success of verification should be shown to the user; e.g. by displaying a website or updating the own UI.
* After clicking the "Reject"-Button, the failure to verify should be shown to the user.
** The notification should indicate that the onboarding was rejected.

|xref:./integration/onboarding.adoc#workflow-for-farming-software-and-telemetry-systems[Secured Onboarding]
|Telemetry platform

Farming software
a|
* A new endpoint is visible in the certification account.
* The external Id is a valid URN, see xref:./integration/general-conventions.adoc[general requirements].
* The following application information is visible in the agrirouter UI:
** The application name
** The application manufacturer
** A valid support URL is available
** By clicking on the support URL the following information is available:
*** Mail
*** Address
*** Phone number
* After an endpoint was deleted by the user, a new onboarding has to be possible.
* In case of any error during the onboarding (with the same (re-onboarding) or a different external Id (new onboarding)):
** An error message is shown to the user (**Remark:** During onboarding, there is always a UI available).
** The error message includes the error code returned from agrirouter.
** The error code does not simply copy the error message from agrirouter.
** Error codes that might not yet be documented have to be displayed as well.
* After onboarding, if not using router devices, the time of certificate expiration needs to be visible to the user (might be hidden in an "advanced" view or similar)

|xref:./integration/revoke.adoc[Revoking]
|Telemetry platform

Farming software
a|
* The specific endpoint disappears from the certification account.
* After an endpoint was deleted by the user, revoking has to be possible.


|xref:./integration/reonboarding.adoc[Re-onboarding]
|Always

(if the application does not use router devices)
a|
* The application instance uses the same external Id as it has used for onboarding.
* New credentials can be provided to communicate with agrirouter.
* After a successful re-onboarding, the endpoint has to communicate with agrirouter using those new credentials.
* An application instance can also be re-onboarded with the same id if it was deleted in the agrirouter UI or revoked before.
* In case of the following errors, an error message is required:
** Wrong account: During re-onboarding, the user is logged in with a different agrirouter account than before. This should result in a new endpoint onboarding in a different account.


|xref:./router-devices.adoc[Updating RouterDevice]
| Farming Software

Telemetry Platforms

(If the application uses router devices)
a|
* The app provider has to demonstrate that he is able to replace the router device with a new one and that the communication via this new router device can be continued.
(A restart of the application is allowed)


|xref:./commands/cloud.adoc#onboarding-a-virtual-cu[VCU onboarding]
|Telemetry platform
a|
* A new endpoint representing the VCU shows up in the certification account.
* The external Id is a valid URN, see xref:./integration/general-conventions.adoc[general requirements]
* A notification is shown in the UI of the telemetry platform or the VCU that informs the user about the successfull onboarding.
* In case of an error, a notification is shown in the UI of the telemetry platform or the VCU that informs the user about the reason.

|xref:./commands/cloud.adoc#removing-a-virtual-cu[VCU offboarding]
|Telemetry platform
a|
* The specific endpoint disappears from the certification account.
* In case of an error, a notification is provided to the initiator of the offboarding
|====

=== Based on commands

It will be checked in advance by the certification company, which commands are supported by your software in which characteristic. Those will be checked. Here is an overview of the commands:

[cols="1,2,9",options="header",]
|====
|Message type |Condition |Expected results / Acceptance criteria
|xref:./commands/endpoint.adoc#capabilities-command[dke:capabilities]
| Always
a|
* Setting routes (as sender or/and as receiver) is possible.
* All information types defined in the certification version of the application to be certified can be selected.

|xref:./commands/endpoint.adoc#subscription-command[dke:subscription]
|If the application can receive messages.
a|
* The application receives published messages of every technical message type mentioned in its certification version as a recipient.

* An application can optionally offer the possibility to deactivate subscriptions for specific message types. During certifications, all subscriptions are required.

|xref:./commands/feed.adoc#call-for-message-header-list[dke:feed_header_query]
|If application can receive messages.
a|
* see __"Clean your feed"__

|xref:./commands/feed.adoc#call-for-messages[dke:feed_message_query]
|If application can receive messages.
a|
* see __"Clean your feed"__

|xref:./commands/feed.adoc#call-for-message-list-confirmation[dke:feed_confirm]
|If application can receive messages.
a|
* see __"Clean your feed"__

|xref:./commands/feed.adoc#call-for-message-deletion[dke:feed_delete]
|If application can receive messages.
a|
* see __"Clean your feed"__

|xref:./commands/ecosystem.adoc#call-for-filtered-list-of-endpoints-that-support-a-specific-message-type[dke:list_endpoints]
|Optional, if supported.
a|
* The application instance receives a list of endpoints to which messages of a certain type can be sent.

|xref:./commands/ecosystem.adoc#call-for-endpoints-that-support-a-technical-message-type[dke:list_endpoints_unfiltered]
|Optional, if supported.
a|
* The application instance receives a list of endpoints to which messages of a certain type can be sent (not considering routing rules)

|xref:./tmt/efdi.adoc#iso11783-10device_descriptionprotobuf---teamsetefdi-device-description[iso:11783:-10:device_description:protobuf]
|If application can send messages.
a|
* If the application reports machines connected via ISOBUS, the AEF conformance test "TaskController" is advised.
* If the application reports self-built device descriptions (e.g. by translating a TractorECU or using Bluetooth beacons), the reported device descriptions have to be compatible with ISO11783-10 Annex F.

|xref:./tmt/efdi.adoc#iso11783-10time_logprotobuf---efdi-timelog[iso:11783:-10:time_log:protobuf]
|If application can send messages.
a|
* see __"Teamset reports"__

|====

=== Applications sending messages
[NOTE]
=====
These tests are only required if your application can send messages.
=====

[cols="1,2,9",options="header",]
|====
|Message type |Condition |Expected results / Acceptance criteria
|xref:./integration/build-message.adoc#chunking-big-messages[Building chunks]
| xref:./tmt/overview.adoc[All TMTs except for EFDI and gps:info]
a|
* The sending of a file with a size of more than 1 MB is possible. The chunks context information is filled.
* The `chunkContextId` is equal for all chunks that represent 1 file.
* The `chunkContextId` changes when a new file is sent.
* The chunks have to be enumerated in `ChunkComponent.current` starting from 1, `ChunkComponent.total` has to equal the highest chunk number
| Base64 encoding
|xref:./tmt/overview.adoc[All TMTs except for EFDI and gps:info]
a|
* A file that should be sent is encoded in Base64.
* If multiple chunks are required, each chunk is a valid Base64 string.
| Sending gps:info and/or EFDI
| App can send gps:info and/or EFDI
a| * GPS Position Lists are not Base64-Encoded
* EFDI Datasets are not Base64-encoded
| Exchange zipped folders
| xref:./tmt/taskdata.adoc[TaskData] and xref:./tmt/shape.adoc[Shape]
a|
* The `TaskData.zip` and / or `Shape.zip` are valid zip files that can be unpacked.

|Message addressing
| Always; optional, if supported.
a|
* Sending a message directly to one recipient.
* Sending a message directly to multiple recipient.
* Publishing a message.
* Publishing a message and sending it directly to 1 recipient.
* Publishing a message and sending it directly to multiple recipient.
|====


=== Applications receiving messages
[NOTE]
=====
These tests are only required if your application can receive data.
=====

[cols="1,2,9",options="header",]
|====
|Message type |Condition |Expected results / Acceptance criteria
|Merging chunks
| xref:./tmt/overview.adoc[All TMTs except for EFDI and gps:info]
a|
* The receiving of a file that consists of 1 chunk without chunk context is possible.
* The receiving of a file that consists of 1 chunk with chunk context is possible.
* The receiving of a file that consists of 2 chunks is possible.
* The receiving of a file that consists of more than 2 chunks is possible.
* The receiving of a file of multiple chunks, which are not delivered in the right order is possible.
| Receive gps:info and EFDI
| App can receive gps:info and/or EFDI
a| * The application can receive gps:info and EFDI that are not Base64-encoded
|Receive Base64 encoded TMTs
| xref:./tmt/overview.adoc[All TMTs except for EFDI and gps:info]
a|
* The receiving of a file that is base64-encoded is possible.
|xref:./integration/push-notification.adoc[Push notifications]
|Always (if supported).
a|
* It is tested if push notifications are activated in the xref:./commands/endpoint.adoc#capabilities-command[capabilities message].
* It is tested if pushed messages are confirmed by the application after receiving them.
* There has to be a concept for the case if push notifications are not delivered from the AR because an outage appeared or the push notification gets lost in another way. We recommend to check the feed at least once a day for messages that were not delivered via push notification.
|====


=== Other requirements
[cols="1,3,3",options="header",]
|====
|Topic |Description |Expected results / Acceptance criteria
|Timestamps{fn-sdk-relaxed}
a| It will be tested that the software uses UTC Timestamp for every message it sends. See also the xref:./integration/general-conventions.adoc[general conventions].
a|
* It's checked if sent messages are in a range of +/- 1 minute of UTC.

|Id requirements{fn-sdk-relaxed}
| There are several general requirements on counters and Ids communicated to agrirouter.
a|
* Every application message Id has to be a UUId.
* On every start up, the sequence number needs to start at 1 and has to be incremented with every command / message.
* The xref:./integration/general-conventions.adoc#string-identifiers-convention[external Id requirements] will be checked.

|Billing requirements
| To avoid problems during the invoicing and billing process, there are some requirements to support the whole process.
a|
* The application should save the `accountId` provided during the onboarding process. The account ID is part of the billing / invoicing and can used to check the invoice, therefore, it should be saved.

| Account management
|If supported, it is checked if the application / communication unit correctly changes the agrirouter endpoint used for the communication when changing the account internally.
a|
* After creating a new account / user in the application to be certified, the test steps have to be repeated with the new account.
* Differentiation between different accounts exists.
* No messages are sent to a wrong account.

|Teamset reports
|The application to be certified needs to report teamsets and provide unique teamset Ids.
a|

* A change of the machine configuration (adding a machine) leads to a new machine in the agrirouter UI.
* A change of the machine configuration (removing a machine) leads to a new teamset context Id.
* A change of the machine configuration (changing a device description) leads to a new teamset context Id

|Clean your feed
a|Make sure, your feed will be cleaned by confirming or deleting messages after receiving them.
[NOTE]
====
For the certification, the rule of cleaning your feed applies with a shorter period of time to clean it, just by practical reasons of the certification. Please check the specific time periods with your certification company.
====
a|
* After the several tests of receiving or rejecting messages, it will be checked if the feed is empty.
* All messages are removed from the feed of the endpoint (either be deleting or receiving and confirming) within a certain period of time.

|Valid commands{fn-sdk-relaxed}
|The application to be certified has to show that it can build and send all commands relevant for its implementation without producing an ACK_WITH_FAILURE at agrirouter mentioning an invalid message.
a|

* All relevant all commands for the implementation can be built and sent without producing an ACK_WITH_FAILURE at agrirouter mentioning an invalid message

| Error handling
a| All errors that show up during communication with agrirouter need to be documented by the application to be certified.

a|
* Application has to document or display any error that occurs in communication with agrirouter. In particular:
** agrirouter system messages
** agrirouter validation messages

* The application provider can show an error message received from agrirouter to the certification company. This can be an administration functionality (e.g. log or UI).
* Error messages shown to an end user should include the error code and a self-defined message of the application provider (not just the SAP error message).

| Buffering
| If the Internet connection gets lost or agrirouter is not available for another reason, the application instance should buffer data that needs to be sent when the connection is re-established.

The application instance needs to check for reconnection on its own.
a|
* It is checked if an application instance keeps trying to communicate with agrirouter when it is not available.
* It is checked if an application instance will retry to send a dataset that should have been sent when the agrirouter was offline. This applies for EFDI as well as for every other technical message type

| Test coverage for Telemetry platform
a| For Telemetry platform, it will be checked in advance of the test, which functionalities are required for the platform itself and which functionalities are required for its Virtual CUs.

Telemetry platform must at least support the onboarding and offboarding of VCUs as well as the secured onboarding and authorization.

Tests are setup depending on the capabilities of the telemetry platform itself and its VCUs.

a|
* All requirements described above need to work with 2 different VCUs and - if sending and/or receiving is supported by the platform itself - by the Telemetry platform.

| Base64 Encoding
a| Base64 Encoded strings shall *not* include line breaks. 
a| Neither Base64 encoded files nor the Base64-encoded messages may include line breaks
|====

=== Message protocol layer and message format

If your software supports REST or MQTT with JSON, sending and receiving of those formats is checked.

If your software supports REST with native Protobuf, sending and receiving of those formats is checked.

==== For HTTP REST

[cols="1,3,3",options="header",]
|====
|Topic |Description |Expected results / Acceptance criteria
|Polling |It is checked that your application does not flood agrirouter with polls |The application shall not poll the outbox of each app instance more often than described xref:./messaging-workflow.adoc#request-sending-frequency[here].
|====

== Recertification cases

An application has to be re-certified if one of the following things apply:

* A new technical message type and/or direction is supported by your application
* The basic message protocol (MQTT or REST) has changed
* The basic message format (JSON or native Protobuf) has changed
* The list of implemented commands changed
* Push notifications are activated in the capabilities

[IMPORTANT]
====
The supported TMTs as well as the used protocol and format are assigned to the certification. A change of any of those functionalities will cause an invalidity of the certificate, which will block your applications communication to agrirouter.
====

[IMPORTANT]
====
In the unlikely event of an update of agrirouter software, which requires changes in the app providers software (e.g. a new error code that shall be handled), a new certification is *not required*. However, the app provider is responsible for keeping his software up to date.
====
