= What is the agrirouter?

:imagesdir: assets/images

image::agrirouter.svg[agrirouter,240]

More information on agrirouter can be found xref:general.adoc[here]

== Basic Concepts

.The agrirouter ecosystem of members
image::general/ecosystem.svg[The agrirouter ecosystem of members,642,321]

As a developer it's also important to understand the xref:basic-concepts.adoc[basic concepts]


**NOTE**
====
In September 2024, agrirouter received a major rebuild. Check out the xref:ar2/summary.adoc[summary of changes] for improvements and changes that might impact your solution or provide new opportunities. 

The rebuild of agrirouter ("agrirouter 2.0") was done with a strong focus on simplification and backwards compatibility.
====

== Purpose of this documentation

The purpose of this documentation is to create deep knowledge about the third party integration into the agrirouter solution. It shall include all information necessary to develop an integration with the agrirouter interface in an application.


== Call for Participation

This documentation is an open source project. We invite everybody to open issues, fork the documentation or create pull requests to fix or extend this documentation.

== Adding your solution to agrirouter
There are three streams that need to be completed to become a part of the agrirouter eco system.

For more details see: xref:partner-process/becoming-a-partner.adoc[]

== Quicklinks
For advanced developers, here is a list of quick links for the most common topics

=== Concepts & Definitions:

* xref:basic-concepts.adoc[Basic concepts of agrirouter]
* xref:glossary.adoc[Glossary]
* xref:terms.adoc[Terms or "agrirouter in a nutshell"]
* xref:ids-and-definitions.adoc[Ids and their  correspondance to each other]

=== Lists

* xref:tmt/overview.adoc[List of Technical Message Types]
* xref:commands/overview.adoc[List of Commands for the agrirouter interface]
* xref:keys.adoc[The agrirouter keys]
* xref:error-codes.adoc[Error Codes]
* xref:integration/environments.adoc[Environments]
* xref:urls.adoc[Relevant URLs]

=== Support
* xref:service-support.adoc[Service & Support]
* xref:training.adoc[Training]
* xref:maintenance.adoc[Maintenance of applications]

=== Tools

There are several tools to support you in your agrirouter development

** xref:tools/io-tool/overview.adoc[IO-Tool - Simulate communication]
** xref:tools/arts.adoc[ARTS - Analyse messages]
** xref:tools/paho.adoc[PAHO - MQTT Testing]



