= Concepts of Telemetry Platform and Virtual CU

== Introduction

Telemetry Platforms are cloud systems that bundle the communication of multiple communication units and are also used to translate the proprietary communication between the communication units and the cloud platform to the agrirouter communication protocol described in this documentation. 

.Telemetry Platforms are cloud systems that communicate for multiple CUs
image::graphs/telemetryplatform.svg[Telemetry Platforms are cloud systems that communicate for multiple CUs,619,366]


=== Endpoint of a telemetry platform

A telemetry platform can communicate in behalf of itself and all of its Virtual CUs.
All communication is performed between that telemetry platform and its in- and outbox.
However, it is important to understand that the telemetry platform itself as well as each virtual CU has its own Feed, Endpoint List, Subscription and Capabilities. To communicate with these specific part of the endpoint, the sensorAlternateId of the relevant partner (telemetry platform itself or one of its Virtual CUs) has to be used. For example if the feed of Virtual CU 1 shall be read, the message has to include the sensorAlternateId of this Virtual CU and not the one of the platform.

The telemetry platform handles the on- and offboarding of virtual CUs, therefore, the sensorAlternateId in every on- and offboarding message for virtual CUs has to be the sensorAlternateId of the telemetry platform itself.

.Telemetry Platforms only share an in- and outbox with their virtual CUs
image::graphs/telemetryconcept.svg[Telemetry Platforms only share an in- and outbox with their virtual CUs,619,366]

=== Commands

Telemetry platforms offer commands to on- and offboard virtual CUs. Those can be found in the xref:./commands/cloud.adoc[Cloud command list].

=== Capabilities

==== In the UI: Summarized capabilities 

When xref:./applications.adoc#_register_application[creating a telemetry platform in the agrirouter UI], the capabilities have to be selected. For a telemetry platform, the capabilities selected in the UI summarize all capabilities of the platform itself as well as any Virtual CU that could be onboarded through the telemetry platform. This means that if your telemetry platform has its own functionalities (e.g. an integrated Farm Management System), those capabilities have to be selected as well.


==== After onboarding the telemetry platform

The xref:./commands/endpoint.adoc#_capabilities_command[capabilities command] has to be sent directly after onboarding the telemetry platform. A telemetry platform that has no own functionality and is only used to onboard and delete virtual CUs does not have any capabilities, so an empty capabilities command has to be sent.

==== After onboarding a virtual CU

After onboarding a virtual CU, the capabilities command for this virtual CU has to be sent, indicating only those capabilities that the virtual CU really is capable of.
