= Handling new versions and updates
:imagesdir: _images/
:toc:
:toc-title:
:toclevels: 4

== General
Changing the software version of your app might require a change in agrirouter if you decide to add new technical message types.

=== When is a new certification version required?
agrirouter is not interested in any internal changes of your software.
However, whenever the maximum capabilities of your software change, you'll need to create a new version in the agrirouter UI and run a new certification.

=== What has to be done?
==== While development
1. You have to create a new certification version in the agrirouter UI
2. After testing, a certification has to be done

==== On deployment and after software update
After update, the app instance has to inform agrirouter about its new capabilities by sending its new capabilities including the ID of the new certification version (certificationVersionId).

=== Safe updates
When updating your software, the onboarding information received from xref:./integration/onBoarding.adoc[onboarding] must be stored so that it is not deleted during update.

If the data gets lost during update, your software can still perform the xref:./integration/reonboarding.adoc[reonboarding] if you can reconstruct the uniqueID used in onboarding, but this might require user interaction.

To use new capabilities after a software update that includes a new CertificationVersionId, an updated capabilities-request using the new CertificationVersionId is required.

===
