= agrirouter Integration Guide

[abstract]
== Abstract
image::agrirouter.svg[agrirouter]

The agrirouter is a universal data exchange platform for farmers and agricultural contractors that makes it possible to connect machinery and agricultural software, regardless of vendor or manufacturer. Agrirouter does not save data; it transfers data.
As a universal data exchange platform, agrirouter fills a gap on the way to Farming 4.0. Its underlying concept unites cross-vendor and discrimination-free data transfer. You retain full control over your data. Even data exchange with service providers (e.g. agricultural contractors) and other partners is uncomplicated: Data are very rapidly transferred via the online connection, and if you wish, is intelligently connected to other datasets.

== Terms and short descriptions

A short description naming all the agrirouter specific terms and their connection to each other can be found link:/terms.adoc[here]

== Tools and Libraries

A list of tools for the agrirouter development as well as a list of libraries and usefull development resources can be found link:/development_resources.adoc[here].

== Certification

Every app needs to be certified to communicate with the agrirouter. Further information can be found link:./certification.adoc[here].

== Marketplace

Once, your app is certified, it can be displayed at the marketplace. Learn mor about that link:./marketplace.adoc[here].

== Application and Endpoint management

Learn, how to handle your applications endpoints link:/application_endpoint_management.adoc[here].

== Service & Support

For feature- or bug reports, you can contact the support. See link:./service_support.adoc[here]


