= agrirouter-interface-documentation
:imagesdir: assets/images
:toc:
:toc-title:
:toc-levels: 4

[abstract]
== Abstract
++++
<p align="center">
 <img src="./assets/images/agrirouter.svg">
</p>
++++

The agrirouter is a universal data exchange platform for farmers and agricultural contractors that makes it possible to connect machinery and agricultural software, regardless of vendor or manufacturer. Agrirouter does not save data; it transfers data. As a universal data exchange platform, agrirouter fills a gap on the way to Farming 4.0. Its underlying concept unites cross-vendor and discrimination-free data transfer. You retain full control over your data. Even data exchange with service providers (e.g. agricultural contractors) and other partners is uncomplicated: Data are very rapidly transferred via the online connection, and if you wish, is intelligently connected to other datasets.

=== The current project you're looking at

This repository includes the documentation of the interface for the agrirouter solution.
Its main purpose is to allow developers to onboard their applications to the agrirouter.

== Purpose of this documentation

The purpose of this documentation is to create deep knowledge about the third party integration into the agrirouter solution. It shall include all information necessary to develop an integration with the agrirouter interface in an application.

== Call for Participation

This documentation is an open source project. We invite everybody to open issues, fork the documentation or create pull requests to fix or extend this documentation.


= Documentation

== Registration

To start the development, you will need to link:./docs/registration.adoc[create an account].


== Terms and short descriptions

A short description naming all the agrirouter specific terms and their connection to each other can be found link:./terms.adoc[here]

A list of shortings can be found link:./docs/shortings.adoc[here]

A glossary can be found link:./docs/glossary.adoc[here]

There are several ids required for communication, a list of descriptions can be found link:./docs/ids-and-definitions.adoc[here].

== Development Resources

A list of tools for the agrirouter development as well as a list of libraries and usefull development resources can be found link:./docs/development-resources.adoc[here].

The keys and certificates required for communication can be found link:./docs/keys.adoc[here].

== Certification

Every app needs to be certified to communicate with the agrirouter. Further information can be found link:./docs/certification.adoc[here].

== Marketplace

Once, your app is certified, it can be displayed at the marketplace. Learn more about that link:./docs/marketplace.adoc[here].

== Application and Endpoint management

For communication with agrirouter, you need to setup an link:./docs/applications.adoc[application].


Learn, how to manage your applications endpoints link:./docs/application-endpoint-management.adoc[here].

== Service & Support

For feature- or bug reports, you can contact the support. See link:./docs/service-support.adoc[here]

In case you experience unexpected connection issues, also check the availability of agrirouter at the link:https://my-agrirouter.com/support/system-status[Status Page].

[Important]
====
This status page shows the availability of the productive environment!
====

== Integration

The integration with agrirouter is described in the link:./docs/general-integration-process.adoc[general integration process].

The following chapters describe all requirements to integrate an application with agrirouter.

=== Before we begin
First, you should always keep in mind the link:./docs/integration/general-conventions.adoc[General conventions].

There are several environments for test and production in different areas of the world. They can be found in the link:./docs/integration/environments.adoc[Environments].

=== Connecting your app instance
FarmingSoftware and Telemetry Platforms have to perform an link:./docs/integration/authorization.adoc[Authorization Process] to clarify, that the account user is known. CUs may also perform it, but that is not required.

To communicate with the agrirouter, an application Instance needs to be link:./docs/integration/onboarding.adoc[onboarded]. An application instance can be link:docs/integration/reonboarding.adoc[ReOnboarded] or all application instance of a specific customer can be link:docs/integration/revoke.adoc[Revoked].

=== Some information on the concepts

For further communication, it's important to understand the link:./docs/endpoint.adoc[Elements of an endpoint] and the link:./docs/communication.adoc[Basics of Communication].

When developing a telemetry platform, the link:./docs/telemetry-platform-concepts.adoc[concepts of a telemetry platform] should be understood.

=== Communicate with agrirouter


To send a message, it has to be built first. Read link:./docs/integration/build-message.adoc[here] about building messages and commands.

Every application instance can link:./docs/integration/message-sending.adoc[send messages] and commands the same way.

While link:./docs/tmt/overview.adoc[messages] are meant to be forwarded to other endpoints, link:./docs/commands/overview.adoc[commands] are used to link:./docs/commands/ecosystem.adoc[explore the ecosystem], link:./docs/commands/endpoint.adoc[configure your endpoint] and link:./docs/commands/feed.adoc[request messages from the feed].

Command results and messages from other endpoints will be link:./docs/integration/message-receiving.adoc[received through the outbox] by the receiving application instance.

Messages from other endpoints are put into the outbox by link:./docs/integration/push-notification.adoc[push notifications] as well as by link:./docs/commands/feed[requesting the feed content].


Depending on the  link:./docs/integration/analyze-result.adoc#ResponseType[resultType], the Result can be link:./docs/integration/analyze-result.adoc[analyzed].

=== Testing the application
Before publishing the app for everyone, it should be tested. Therefore, you can link:./docs/invite-testers.adoc[invite beta testers] from your developers account.

=== Usage metrix

As an application provider, you can download link:./docs/usage-metrix.adoc[usage metrics] to check, which account consumed how much data.

=== Behaviour after SoftwareUpdate
Read here, how to handle link:./docs/update.adoc[new versions and updates].


==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:./README.adoc[Index]|link:./docs/general.adoc[OverView]|link:./docs/shortings.adoc[shortings]|link:./terms.adoc[agrirouter in a nutshell]
|====
