= agrirouter-interface-documentation
:imagesdir: modules/ROOT/assets/images

[abstract]
== Abstract
image::agrirouter.svg[agrirouter]

The agrirouter is a universal data exchange platform for farmers and agricultural contractors that makes it possible to connect machinery and agricultural software, regardless of vendor or manufacturer. Agrirouter does not save data; it transfers data.
As a universal data exchange platform, agrirouter fills a gap on the way to Farming 4.0. Its underlying concept unites cross-vendor and discrimination-free data transfer. You retain full control over your data. Even data exchange with service providers (e.g. agricultural contractors) and other partners is uncomplicated: Data are very rapidly transferred via the online connection, and if you wish, is intelligently connected to other datasets.

== agrirouter Documentation

This project houses the source files for our documentation website https://docs.my-agrirouter.com.

These files get automatically built and deployed on any change in the develop branch.

=== old links

During the documentation structure change in May 2021, all old links became invalid. Please visit https://docs.my-agrirouter.com and navigate to the page you were looking for.
 