= agrirouter-interface-documentation
:imagesdir: assets/images
:toc:
:toc-title:
:toc-levels: 4

[abstract]
== Abstract
image::logo.svg[agrirouter]
The agrirouter is a universal data exchange platform for farmers and agricultural contractors that makes it possible to connect machinery and agricultural software, regardless of vendor or manufacturer. Agrirouter does not save data; it transfers data. As a universal data exchange platform, agrirouter fills a gap on the way to Farming 4.0. Its underlying concept unites cross-vendor and discrimination-free data transfer. You retain full control over your data. Even data exchange with service providers (e.g. agricultural contractors) and other partners is uncomplicated: Data are very rapidly transferred via the online connection, and if you wish, is intelligently connected to other datasets.

=== The current project you're looking at

This repository includes the documentation of the interface for the agrirouter solution.
Its main purpose is to allow developers to onboard their applications to the agrirouter.

= Documentation
The agrirouter integration is currently documented in 2 downloadable files:

== Integration Guide Part 1
This document describes the general functionality of the agrirouter interface and can be found link:\assets\documents\DKE_agrirouter_Integration_Guide_Part_1_v2.3.pdf[here] 

== Integration Guide Part 2
This document includes specific api calls, JSON-and protobuf descriptions and important notes on how to integrate your app with the agrirouter.
It will be uploaded very soon, better watch this repository... 

== System Messages and Message codes
The system message codes can be found link:\docs\SystemMessageCodes.adoc[here]

== External resources

Here are some external resources for the development:

 *  https://www.my-agrirouter.com[my-agrirouter.com Website]
