= agrirouter-interface-documentation
:imagesdir: assets/images
:toc:
:toc-title:
:toc-levels: 4

[abstract]
== Abstract
++++
<p align="center">
 <img src="./assets/images/agrirouter.svg">
</p>
++++

The agrirouter is a universal data exchange platform for farmers and agricultural contractors that makes it possible to connect machinery and agricultural software, regardless of vendor or manufacturer. Agrirouter does not save data; it transfers data. As a universal data exchange platform, agrirouter fills a gap on the way to Farming 4.0. Its underlying concept unites cross-vendor and discrimination-free data transfer. You retain full control over your data. Even data exchange with service providers (e.g. agricultural contractors) and other partners is uncomplicated: Data are very rapidly transferred via the online connection, and if you wish, is intelligently connected to other datasets.

=== The current project you're looking at

This repository includes the documentation of the interface for the agrirouter solution.
Its main purpose is to allow developers to onboard their applications to the agrirouter.

= Documentation

The agrirouter integration can be found in the link:./index.adoc[agrirouter Interface Documentation] .

== Old files

before converting to adoc, the documentation was provided in 2 PDF files called "integration guide". Those can be found here:

=== Integration Guide Part 1
This document describes the general functionality of the agrirouter interface and can be found link:./assets/documents/integration-guide-part-1.pdf[here]

=== Integration Guide Part 2
This document includes specific api calls, JSON-and protobuf descriptions and important notes on how to integrate your app with the agrirouter.
The integration guide part 2  can be found link:./assets/documents/integration-guide-part-2.pdf[here]

[WARNING]
====
These files might be outdated and will no longer be updated.
====

== System Messages and Message codes
The system message codes can be found link:./docs/ErrorCodes.adoc[here]

== External resources

Here are some external resources for the development:

 *  https://www.my-agrirouter.com[my-agrirouter.com Website]





==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:./index.adoc[Index]|link:./docs/general.adoc[OverView]|link:./docs/shortings[shortings]|link:./terms.adoc[agrirouter in a nutshell]
|====

