= Table of contents
This document contains a brief overview of the contents of the docmentation.

/assets link:./assets[->] :: The folder contains all immages and other raw data for the documentation.
/ertificates link:./assets/certificates[->] ::: The folder contains the certificates for the connection to the *agrirouter*.
eu-prod-ca-cert.pem link:./assets/certificates/eu-prod-ca-cert.pem[->] :::: The certificate file for the connection to the PROD envrionment of the *agrirouter*.
eu-qa-ca-cert.pem link:./assets/certificates/eu-qa-ca-cert.pem[->] :::: The certificate file for the connection to the QA envrionment of the *agrirouter*.
/images link:./assets/images[->] ::: All images used in the documentation. The content of the directory is not listed explicitly.
errorcodes.xlsx link:./assets/errorcodes.xlx[->] :: Common error codes during the communication with the *agrirouter*. 
/docs link:./docs[->] :: The folder contains all documents.
.gitignore link:./,gitignore[->] :: Technical file, can be ignored.
LICENSE link:./LICENSE[->] :: License information for this project.
README.adoc link:./README.adoc[->] :: Entry point for the documentation and the file that is shown on startup of the page.
