= EFDI
:imagesdir: 

== iso:11783:-10:device_description:protobuf - Teamset/EFDI Device Description

=== Definition

The message iso:11783:-10:device_description:protobuf is used to understand, which machine is attached to which CU or Virtual CU and which machine provides which DDI. EFDI Device Descriptions are protobuf encoded, the data structure however is mainly equal to the form of an ISO11783-10 TaskData.

The proto file definining the format can be found link:https://github.com/DKE-Data/agrirouter-tmt-protobuf-definitions/blob/develop/dotnet/agrirouter/protobuf/technicalmessagetype/efdi.proto[in our Github repository].

This format is used to report devices that are attached to the agrirouter through a CU. These devices including the CU are known as a teamset, having their own teamsetID.

The teamset ID should preferably be a GUID.

[IMPORTANT]
====
The CUs defining the teamset ID have to make sure that they define it  *one-to-one* and, optionally, in a *deterministic* way in regards to the contents of the device_description.

This means that

* every change, even a minor one, in the device_description *has* to lead to a change of the teamset ID (because it will potentially influence the way the respective timelogs have to be decoded) and
* the same device_description *should* result in the same teamset ID

The teamset ID has to change, for example, when

* it is determined by different CUs, even when the same machines are connected
* another machine is being connected
* the device description/DDOP of any machine changes for any reason (software update, configuration change...)
* the order in which a TaskController added machines changes; the following two cases have to produce different teamset IDs:
** Machine A gets assigned DET-1, Machine B gets assigend DET-2
** Machine B gets assigend DET-1, Machine A gets assigend DET-1


====

For information on filtering and assigning machines by their name, see xref:../ecosystem.adoc[ecosystem].

=== Command

[cols=",",]
|==================================================
|Command |iso:11783:-10:device_description:protobuf
|Protobuf Schema |https://github.com/DKE-Data/agrirouter-tmt-protobuf-definitions/blob/develop/dotnet/agrirouter/protobuf/technicalmessagetype/efdi.proto[efdi.ISO11783_TaskData]
|TypeURL |types.agrirouter.com/efdi.ISO11783_TaskData
|==================================================

[NOTE]
====
For the case of Device Description, *only* the property device needs to be filled!
====

=== Result

The result indicates if the teamset could be forwarded to an addressed endpoint or – if it was published – if there was a subscribed endpoint, who received the message. If no endpoint received the message, there will be an ACK_WITH_FAILURE

[NOTE]
====
If a CU sends a teamset, applications are able to address messages directly to the devices. These messages are then delivered to the CU.
====


=== Frequency

In addition to the change-based sending of Device Descriptions described above, it would be beneficial to also send device descriptions

* when the communication unit is powered on
* at a regular interval between once per hour and once per day, depending on the use case and architecture of your solution

While not strictly technically necessary, these steps help in troubleshooting or automatic recovery in case any issues appear.


== iso:11783:-10:time_log:protobuf - EFDI TimeLog

The EFDI timelog is comparable to IOSOXML Binary Log data. 

The Message iso:11783:-10:time_log:protobuf includes a list of live telemetry data. For those live telemetry data, agrirouter is able to select only those DDIs to be forwarded to an endpoint that were selected by the end user when creating routings.

The proto file definining the format can be found link:https://github.com/DKE-Data/agrirouter-tmt-protobuf-definitions/blob/develop/dotnet/agrirouter/protobuf/technicalmessagetype/efdi.proto[in our Github repository].

EFDI Time Logs are as well comparable to ISO11783 TimeLogs.

[IMPORTANT]
====
Make sure that a timelog message never exceeds the limit of 1MB of data. If this should ever be the case in your app,
split this message into multiple timelog messages.
====

include::partial$device-description-has-to-be-sent-every-time.adoc[]

=== Command

[cols=",",]
|==================================================
|Command |iso:11783:-10:time_log:protobuf
|Protobuf Schema |https://github.com/DKE-Data/agrirouter-tmt-protobuf-definitions/blob/develop/dotnet/agrirouter/protobuf/technicalmessagetype/efdi.proto[efdi.Timelog]
|TypeURL |types.agrirouter.com/efdi.TimeLog
|==================================================

== Content of Telemetry messages

=== DDIs

Telematic sensor values are assigned to DDIs, a standardized list of possible sensor and task information. A full list can be found here: https://isobus.net.

The TimeLogs message includes a list of DDI numbers and their corresponding current values. The agrirouter can filter timelog messages for DDIs that are part of a routing. The categories have an informative character. The DDI list provides a number area for proprietary DDIs that can have a specific definition for each manufacturer.

