= Images
:imagesdir: 

== img:bmp - Bitmap Image


=== Definition

This format is used to exchange a bitmap file. It can forward the binary bmp-Content, metadata like the flename can be forwarded using the metadata element in the request.

=== Command

[cols=",",]
|==================
|Command |img:bmp
|Protobuf Schema |-
|TypeURL |"”
|==================

=== Format

The bmp file data has to be transferred in a Base64 representation of its binary data. If the (base64 encoded) file size exceeds the maximum size of a message, it has to be chunked. Each chunk needs to be a valid base64 string, which requires base64 encoding **after** splitting the binary data into chunks.


[NOTE]
====
The base64-encoding of the binary chunk/file data is not the same as the base64 encoding of the message. It is an additional step!
====


== img:jpg – JPEG Image

=== Definition

This format is used to exchange a bitmap file. It can forward the binary jpeg-Content, metadata like the flename can be forwarded using the metadata element in the request.

=== Command

[cols=",",]
|==================
|Command |img:jpg
|Protobuf Schema |-
|TypeURL |"”
|==================

=== Format

The jpeg file data has to be transferred in a Base64 representation of its binary data. If the (base64 encoded) file size exceeds the maximum size of a message, it has to be chunked. Each chunk needs to be a valid base64 string, which requires base64 encoding **after** splitting the binary data into chunks.

[NOTE]
====
The base64-encoding of the binary chunk/file data is not the same as the base64 encoding of the message. It is an additional step!
====

== img:png – PNG Image

=== Definition

This format is used to exchange a bitmap file. It can forward the binary png-Content, metadata like the flename can be forwarded using the metadata element in the request.

=== Command

[cols=",",]
|==================
|Command |img:png
|Protobuf Schema |-
|TypeURL |"”
|==================

=== Format

The png file data has to be transferred in a Base64 representation of its binary data. If the (base64 encoded) file size exceeds the maximum size of a message, it has to be chunked. Each chunk needs to be a valid base64 string, which requires base64 encoding **after** splitting the binary data into chunks.

[NOTE]
====
The base64-encoding of the binary chunk/file data is not the same as the base64 encoding of the message. It is an additional step!
====
