= shp:shape:zip - Shape
:imagesdir: 

== Definition

This format is used to exchange application maps as a zip file, metadata like the filename can be forwarded using the metadata element in the request.

Shape files in agrirouter refer to the de-facto standard for geo-referenced information, created by ESRI. The full specification document can currently be found https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf[on the ESRI website].

There are numerous libraries for different languages to handle reading and writing of this file format.

== Command

[cols=",",]
|======================
|Command |shp:shape:zip
|Protobuf Schema |-
|TypeURL |-
|======================

== Format

The zip file data has to be transferred in a Base64 representation of its binary data. If the (base64 encoded) file size exceeds the maximum size of a message, it has to be chunked. Each chunk needs to be a valid base64 string, which requires base64 encoding **after** splitting the binary data into chunks.

[NOTE]
====
The base64-encoding of the binary chunk/file data is not the same as the base64 encoding of the message. It is an additional step!
====
