= Videos
:imagesdir: 

== vid:avi – AVI Video Files

=== Definition

This format is used to exchange an avi video file. It can forward the binary avi-Content, metadata like the filename can be forwarded using the metadata element in the request.

=== Command

[cols=",",]
|==================
|Command |vid:avi
|Protobuf Schema |-
|TypeURL |-
|==================

=== Format

The avi file data has to be transferred in a Base64 representation of its binary data. If the (base64 encoded) file size exceeds the maximum size of a message, it has to be chunked. Each chunk needs to be a valid base64 string, which requires base64 encoding **after** splitting the binary data into chunks.
[NOTE]
====
The base64-encoding of the binary chunk/file data is not the same as the base64 encoding of the message. It is an additional step!
====

== vid:wmv – WMV Video Files

=== Definition

This format is used to exchange an wmv video file. It can forward the binary wmv-Content, metadata like the filename can be forwarded using the metadata element in the request.

=== Command

[cols=",",]
|==================
|Command |vid:wmv
|Protobuf Schema |-
|TypeURL |-
|==================

=== Format

The wmv file data has to be transferred in a Base64 representation of its binary data. If the (base64 encoded) file size exceeds the maximum size of a message, it has to be chunked. Each chunk needs to be a valid base64 string, which requires base64 encoding **after** splitting the binary data into chunks.

[NOTE]
====
The base64-encoding of the binary chunk/file data is not the same as the base64 encoding of the message. It is an additional step!
====

== vid:mp4 – MPEG4 Video Files

=== Definition

This format is used to exchange an MPEG4 video file. It can forward the binary mp4-Content, metadata like the filename can be forwarded using the metadata element in the request.

=== Command

[cols=",",]
|==================
|Command |vid:mp4
|Protobuf Schema |-
|TypeURL |-
|==================

=== Format

The mp4 file data has to be transferred in a Base64 representation of its binary data. If the (base64 encoded) file size exceeds the maximum size of a message, it has to be chunked. Each chunk needs to be a valid base64 string, which requires base64 encoding **after** splitting the binary data into chunks.

[NOTE]
====
The base64-encoding of the binary chunk/file data is not the same as the base64 encoding of the message. It is an additional step!
====
