= Environments

agrirouter currently supports 2 environments of the whole agrirouter connectivity platform.

== Quality assurance

The quality assurance environment (“QA”) is used to develop and test applications in a save and uncritical eco system. Please note, that the quality assurance environment shall not be used by end customers.

== Productive

The productive environment is used by your end customers with tested and certified apps. This environment is very scalable and made for a huge number of users.

== Areas

Currently, there is only one Area: EU1. Every app instance is onboarded to environments in this area. With upcoming availability of the agrirouter in more and more countries, there might be additional areas created. This could happen for performance reasons or legal requirements of different countries. If new areas become required, this document will be updated, providing all the required information.






==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:../../index.adoc[Index]|link:../general.adoc[OverView]|link:../shortings[shortings]|link:../../terms.adoc[agrirouter in a nutshell]
|====