= Receiving Results
:imagesdir: ./../assets/images/
:toc:
:toc-title:
:toclevels: 4


== General

Results for commands and messages from calls for messages are returned to the outbox. An application instance receives them from the outbox and can than decode the data.


[IMPORTANT]
====
*Any feed query message has to be confirmed to be deleted from the feed. If you do not confirm a feed message, you will receive it over and over again, until you confirm it.*
====

== MQTT

The endpoint address of the MQTT broker is delivered as host+port in the onboarding request. The outbox is the topic delivered with the “commands” attribute of the onboarding request. The app instance has to subscribe for this topic.

//TODO The addresses can be found in chapter 14.2Using MQTT.

== REST

The REST endpoint address of the outbox is delivered with the “command” attribute of the onboarding request.

An application Instance has to perform a GET request to this endpoint to receive all messages from the outbox.

[cols="1,4",options="header",]
|=======================================================
|Method |Adress
|GET |/iot/gateway/rest/commands/{{deviceAlternateId}}
|=======================================================


== Format of received messages

Agrirouter returns an array of messages, so, there can be multiple responses in one response package.

The result format depends on the setting of the Accept-Header in the GET Request to the Outbox:

[cols=",",options="header",]
|=======================================
|Accept Header |Will Receive
|application/json |JSON
|application/x-protobuf |Native Protobuf
|=======================================

=== JSON Result
[source,javascript]
----
[

    {

        “sensorAlternateId”: “49dcf152-eb2a-4b50-ad5c-1af5b737ed80”,

        “capabilityAlternateId”: “49dcf152-eb2a-4b50-ad5c-1af5b737ed80”,

        “command”: {

            “message”: “fskjlaflasdfkjlasdfkjfalkefnFSDLKDFJL33221sdldgkjglfdkjldkgjDFAFKJLKJSFDSFEESXFRRDGDGRDGDGRSDDGRddrrrg354grdgIODIO35445DGDGLKKJWE3333425H1SJK==”

        }

    }

]
----

=== Protobuf Result
[source,javascript]
----
syntax = "proto3";

import "google/protobuf/any.proto";

package gateway;

option java_package = "com.sap.iotservices.common.protobuf.gateway";

option java_outer_classname = "CommandResponseProtos";

message CommandResponse {

    string capabilityAlternateId = 1;

    string sensorAlternateId = 2;

    Command command = 3;

    message Command {

     repeated google.protobuf.Any values = 1;

    }

}
----

[source,javascript]
----
syntax = "proto3";

import "CommandResponse.proto";

package gateway;

option java_package = "com.sap.iotservices.common.protobuf.gateway";

option java_outer_classname = "CommandResponseListProtos";

message CommandResponseList {

    repeated CommandResponse commands = 1;

}
----

=== ParameterList

The result of a request to the outbox is an *array* of messages each including the following parameters:

[cols="2,1,4",options="header",]
|=======================================================================================================
|Name |Type |Description
|capabilityAlternateId |String |Equals value from onboarding
|sensorAlternateId |String |Source of the message
|command |String |The Base64 encoded message or a protobuf object, if agrirouter sent a protobuf object.
|=======================================================================================================

As this Array can include multiple messages, all further steps need to be done in a loop.

