= Certification process
:imagesdir: ./../assets/images/
:toc:
:toc-title:
:toclevels: 4


== In General

Every application needs to be certified to be onboardable to the agrirouter. The certification process ensures, that the communication protocol of the agrirouter is successfully implemented and the application is able to communicate correctly with the agrirouter.

A certification is needed any time, the app changes its capabilities, changes the commands or uses a different protocol to communicate with the agrirouter.

[NOTE]
=====
For a new certification version, capabilities can never be removed. It is only allowed to add capabilities for a new version. The capabilities request however can of course only include a subset that is smaller than in the version before.
=====

== Out of focus

The certification will not check, if an application is able to work with the data sent over the agrirouter. The process will only check, if the application can send and receive data for the technical message types, that were selected for the certification version.

== Certification institutes

DKE and the agrirouter support team will release a list of certified partners, who are able and allowed to certificate applications. Please refer to https://my-agrirouter.com/support/downloads/ for all information regarding the certification institutes.

== Certification tests
Not all of the certification tests are necessary for your implementation, the selection depends on several parameters:

== Always necessary
The following parts are always necessary:


* link:./integration/reonboarding.adoc[Reonboarding]

* link:./commands/endpoint.adoc#capabilities-command[Sending the capabilities] 
[REMARK]
=====
The capabilities reported through the capabilities command may not include more capabilities then reported in the agrirouter UI when setting up the certification version.
To pass the test, every listed technical message type from certification version needs to be exchanged in the reported directions. 
=====
* **Clean your feed**: After the several tests of receiving or rejecting messages, it will be checked if the feed is empty. So: Make sure, your feed will be cleaned by either requesting and confirming or deleting messages

=== Type of application

Which kind of application do you develop?::

* Communication unit (CU)
    . The link:./integration/onboarding.adoc[Onboarding procedure] is necessary.

* Telemetry platform or farming software
    . The link:./integration/authorization.adoc[authorization process] is necessary.
    
    . The link:./integration/onboarding.adoc#workflow-for-farming-software-and-telemetry-systems[secured onboarding] is necessary.


    . link:./integration/revoke.adoc[Revoking] is required
    
=== Protocol layer

Which communication protocol and format do you want to use?::

* REST via HTTP
** Do you use JSON?
. All certification steps are performed using encoded JSON for the tests.

** Do you use native protobuf?
. All certification steps are performed using native protobuf for the tests.
    
* MQTT
** Do you use router devices?
. All tests are done using a link:./communication.adoc[router device] which was onboarded within a given account.

** Do you use single endpoints?
. All tests are done using the credentials delivered while onboarding endpoints within a given account.

=== Sending messages

* Is your application able to send EFDI?
. Setting the `TeamsetContextID` and changing it, when the machine configuration changes is necessary.

* Is your application able to send technical message types except for EFDI?
. The link:./integration/build-message.adoc#chunking-big-messages[chunking mechanism] to create chunks is necessary.

* Does your application want to publish data?::
. Your software must link:./commands/ecosystem.adoc[request the endpoint list], so that you can make sure you don't publish data without any recipient available

=== Receiving messages

* Is your application able to receive technical message types except for EFDI?
. The link:./integration/build-message.adoc#chunking-big-messages[chunking mechanism] to merge chunks is relevant

* Is your application able to support push notifications?
. It's tested, if push notifications are activated in the link:./commands/endpoint.adoc#capabilities-command[capabilities message]
. It's tested, if pushed messages are confirmed

=== For Telemetry platforms
If your app does perform as a telemetry platform, you need to support::
* link:.commands/cloud.adoc[Cloud onboarding]
* link:./commands/cloud.adoc#removing-a-virtual-cu[Cloud offboarding]
* Sending link:./commands/endpoint.adoc#capabilities-command[capabilities message] in behalf of the VCU
* link:./commands/feed.adoc[Reading feed] in behalf of the VCU

==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:../README.adoc[Index]|link:./general.adoc[OverView]|link:./shortings.adoc[shortings]|link:../terms.adoc[agrirouter in a nutshell]
|====