= Certification process
:imagesdir: ./../assets/images/
:toc:
:toc-title:
:toclevels: 4


== General

Every Application needs to be certified to be onboardable to the agrirouter. The certification makes sure, that the communication protocol of the agrirouter was successfully implemented and the application is able to communicate with the agrirouter.

A certification is needed any time, the app changes its capabilities.

== Out of focus

The certification will not check, if an application “understands” the data sent over agrirouter, it will only check, if the application can send and receive data marked as such Technical message types, that were selected in the Certification Version.

== Certification institutes

DKE and the agrirouter support team will release a list of certified partners, that are able and allowed to do the certification process. Please refer to https://my-agrirouter.com/support/downloads/.

== Relevant Tests
Which tests are relevant for your implementation depend on several factors:

=== Type of application

Which kind of app do you develop?::

* Communication unit (CU)
    . The Onboarding procedure is relevant

* Telemetry Platform or Farming Software
    . The authorization process is relevant
    
    . Secured onboarding is relevant

=== Protocol layer

Which protocol and format do you want to use?::
* HTTP REST
=> **Which Format do you use?**
** JSON
. All tests are done for JSON REST

** PROTOBUF
. All tests ar done using native protobuf
    
* MQTT
=> **Do you use router devices?**

** YES
. All tests are done using a router device

** NO
. All tests are done using the credentials delivered while onboarding

=== Sending messages

Shall your application send EFDI?::
* YES
. Setting the TeamsetContextID and changing it, when the machine configuration changes is relevant.

* NO

Shall your application send Technical Message Types except for EFDI?::
* YES
. The chunking mechanism to create chunks is relevant
* NO

Does your software want to publish data?::
* YES
. Your software must request the endpoint list, so that you can make sure you don't publish data without any receipient available

=== Receiving messages

Shall your application receive EFDI?::
* YES
. 

* NO

Shall your application receive Technical Message Types except for EFDI?::
* YES
. The chunking mechanism to merge chunks is relevant
* NO

Does your app support push notifications?::
* YES
. It's tested, if push notifications are activated in the capabilities message
. It's tested, if pushed messages are confirmed



=== For Telemetry platforms
If your app does perform as a telemetry platform, you need to support::
* Cloud onboarding
* Cloud offboarding
* Sending capabilties in behalf of the VCU
* Reading feed in behalf of the VCU


== Always relevant
The following parts are always relevant:

* Revoking

* Reonboarding

* Sending the capabilities (which need to be a subset of the capabilities mentioned in the version)

* **Clean your feed**: After the several tests of receiving or rejecting messages, it will be checked if the feed is empty. So: Make sure, your feed will be cleaned by either requesting and confirming or deleting messages



==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:../README.adoc[Index]|link:./general.adoc[OverView]|link:./shortings.adoc[shortings]|link:../terms.adoc[agrirouter in a nutshell]
|====

