= Certification process
:imagesdir: ./../assets/images/
:toc:
:toc-title:
:toclevels: 4


== In General

Every application needs to be certified to be onboardable to the agrirouter. The certification process ensures, that the communication protocol of the agrirouter is successfully implemented and the application is able to communicate correctly with the agrirouter.

A certification is needed any time, the app changes its capabilities, changes the commands or uses a different protocol to communicate with the agrirouter.

[NOTE]
=====
For a new certification version, capabilities can never be removed. It is only allowed to add capabilities for a new version. The capabilities request however can of course only include a subset that is smaller than in the version before.
=====

== Out of focus

The certification will not check, if an application is able to work with the data sent over the agrirouter. The process will only check, if the application can send and receive data for the technical message types, that were selected for the certification version.

== Certification institutes


There are multiple certification institutes, a list can be found link:https://my-agrirouter.com/support/certification/[here].


== Certification Requirements

To fullfill the certification, there are several requirements, of which several have to be finished before the certification process can start.

=== Prerequists

*  The link:./provider-agreement.adoc[DKE App Provider Agreement] has to be signed
*  The link:./marketplace.adoc[Marketplace entry] is done with "Coming soon" label
* Following information are available about the company:
** Name
** Address
*  Following information are available for a first level customer support:
** EMail
** Address
** Phone
** URL
* A link:./registration.adoc[Quality Assurance Environment Developer Account]
* ApplicationId and CertificationVersionId of link:./applications.adoc[an Application in the Quality assurance Environment].
* The type of application

== Further requirements

The following information are not necessary to start the process but will be required before finishing it:

* A link:./registration.adoc[Production Environment Developer Account]
* ApplicationId and CertificationVersionId of link:./applications.adoc[an Application in the Production Environment].
* Version, Name and Description of the application to certify
* Communication protocol (MQTT/REST)
* Data format (JSON/Native Protobuf)
* The capabilities of the app including link:./tmt/overview.adoc[the technical message types] and the sending directions
* A list of link:./commands/overview.adoc[all commands], that are used by the app
* Is this an initial certification or a recertification for a new version of an existing software




== Certification tests
Not all of the certification tests are necessary for your implementation, the selection depends on several parameters:

=== Based on the application type

Based on the type of your application, different tests might be required. Check link:./applications.adoc[here], which type suites your requirements best.

[cols=",,",width="100%"]
|============================
>s|CU (Telemetry Connections) >s|Farming Software  >s| Telemetry Platforms
 1.6+^.^|link:./integration/onboarding.adoc[Onboarding] 2.1+^|link:./integration/authorization.adoc[Authorization Process]
 2.1+^|link:./integration/onboarding.adoc#sending-a-verification-request[Verification (Optional, if supported)]
 2.1+^|link:./integration/onboarding.adoc#workflow-for-farming-software-and-telemetry-systems[Secured Onboarding]
 | 1.1+^| link:./commands/cloud.adoc#onboarding-a-virtual-cu[VCU onboarding]
 2.1+^|link:./integration/revoke.adoc[Revoking]
 | 1.1+^| link:./commands/cloud.adoc#removing-a-virtual-cu[VCU offboarding]
 3.1+^|link:./integration/reonboarding.adoc[Reonboarding]
 3.1+^|link:./commands/endpoint.adoc#capabilities-command[Sending the capabilities]
 2.1+|  | link:./commands/endpoint.adoc#capabilities-command[Send Capabilities] (link:./telemetry-platform-concepts.adoc[for each VCU])
 3.1+^|link:./certification.adoc#clean-your-feed[Clean your feed]
 2.1+|  | link:./certification.adoc#clean-your-feed[Clean your feed] (link:./telemetry-platform-concepts.adoc[for each VCU])

|============================

[REMARK]
=====
The capabilities reported through the capabilities command may not include more capabilities then reported in the agrirouter UI when setting up the certification version.
To pass the test, every listed technical message type from certification version needs to be exchanged in the reported directions. 
=====

==== Clean your feed
After the several tests of receiving or rejecting messages, it will be checked if the feed is empty. So: Make sure, your feed will be cleaned by either requesting and confirming or deleting messages. For the certification process, the rule of cleaning your feed applies with a shorter period of time to clean it, just by practical reasons of the certification process. Please check the specific time periods with your certification institute.

==== TimeStamps
It will be tested, that the software uses UTC Timestamp for every message, it sends. See also the link:./integration/general-conventions.adoc[General Conventions].

==== Id requirements

* Every ApplicationMessageId has to be a unique UUID.
* On every StartUp, the Sequence Number needs to start at 1 and has to be incremented with every command/message.
* The link:./integration/general-conventions.adoc#string-identifiers-convention[external ID requirements] will be checked

=== Based on direction
==== Sending messages
[REMARK]
=====
These tests are only required, if your application can send data 
=====

* Is your application able to send EFDI?
. Sending link:./tmt/EFDI.adoc#iso11783-10device_descriptionprotobuf---teamsetefdi-device-description[Device Descriptions] and link:./tmt/EFDI.adoc#iso11783-10time_logprotobuf---efdi-timelog[TimeLog Data] is required
. Setting the `TeamsetContextID` and changing it, when the machine configuration changes is necessary.

* Is your application able to send technical message types except for EFDI?
. The link:./integration/build-message.adoc#chunking-big-messages[chunking mechanism] to create chunks is necessary.
. The correct sending of Base64 encoded data is checked

* Does your application send the TaskData or Shape messageformat?
. The correct sending of the Base64-encoded Zip Folder will be checked.

* Does your application want to send data?
. Your software must link:./commands/ecosystem.adoc[request the endpoint list], so that you can get a list of endpoints and - in case you want to publish data - make sure you don't publish data without any recipient available.

* The adressing will be tested:
** Sending a message to one receipient
** Sending a message to multiple receipients
** Publishing a message
** Publishing a message and sending it directly to 1 receipient
** Publishing a message and sending it directly to multiple receipients


==== Receiving messages
[REMARK]
=====
These tests are only required, if your application can receive data 
=====

* Is your application able to receive technical message types except for EFDI?
. The link:./integration/build-message.adoc#chunking-big-messages[chunking mechanism] to merge chunks is relevant

* Is your application able to support push notifications?
. It's tested, if push notifications are activated in the link:./commands/endpoint.adoc#capabilities-command[capabilities message]
. It's tested, if pushed messages are confirmed

* Supported messages: The following messages will be checked
. link:./commands/feed.adoc#call-for-message-header-list[FeedHeaderQuery]
. link:./commands/feed.adoc#call-for-specific-messages[FeedMessageQuery]
. link:./commands/feed.adoc#call-for-message-deletion[DeleteMessage]
. link:./commands/feed.adoc#call-for-message-list-confirmation[Confirm Message]

* If your application is capable of receiving any technical message type, it is major to link:./commands/endpoint.adoc#subscription-command[subscribe for message types]
[REMARK]
=====
Subscribing is required to receive all messagetypes published to the agrirouter. This is especially required to receive message types published from a different account using the account pairing.

It is optional to en- or disable subscriptions (e.g. by providing a UI), for the certification however it has to be shown, that subscriptions are possible.
=====

    
=== Based on Protocol layer and Data Format

If your software supports REST or MQTT with JSON, sending and receiving of those formats is checked.
If your software supports REST with NativeProtobuf, sending and receiving of those formats is checked.



=== Account management

For CUs: If supported, it's checked, if a CU correctly changes the agrirouter endpoint, it is communicating with, when the account in the CU is changed.


==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:../README.adoc[Index]|link:./general.adoc[OverView]|link:./shortings.adoc[shortings]|link:./terms.adoc[agrirouter in a nutshell]
|====

