= Registration and Login
:imagesdir: ./../assets/images/
:toc:
:toc-title:
:toclevels: 4

== Overview

To create applications for agrirouter, a developer account is required.

After signing the app provider contract, the developer should create 2 accounts:

One account at the productive environment, where the application shall be available to be connected for the end user and one account in the "Quality Assurance"-Environment (QA) to test the application during development.

Here you can signup for the accounts:
[cols="1,2,4",options="header",]
|===========================================================================
|Area |Environment |URL
|EU |Quality Assurance |https://agrirouter-qa.cfapps.eu10.hana.ondemand.com/
|EU |Productive |https://goto.my-agrirouter.com/
|===========================================================================

After creating your account, please also send an email to support@my-agrirouter.com to force the activation of your account. 

[IMPORTANT]
====
There shall only be 1 developer account per app provider. So, if your company has multiple developers, 1 developer should handle the developer account; the other developers can use end user accounts to test and develop the application itself.
====


==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:../README.adoc[Index]|link:general.adoc[OverView]|link:shortings.adoc[shortings]|link:../terms.adoc[agrirouter in a nutshell]
|====

