= iso:11783:-10:taskdata:zip - TaskData
:imagesdir: ./../../assets/images/
:toc:
:toc-title:
:toclevels: 4

== Definition

This format is used to exchange a TaskData.zip Files. It can forward the binary Zip-File-Content, metadata like the flename can be forwarded using the metadata element in the request.

== Command

[cols=",",]
|===================================
|Command |iso:11783:-10:taskdata:zip
|Protobuf Schema |-
|TypeURL |“”
|===================================

== Format

The zip file has to be formatted to a Base64-encoding of its binary data. It must be sent as a string inside the payload wrapper object. The type field can be let empty.


[NOTE]
====
The base64-encoding of the binary file is not the same as the base64 encoding of the message. It is an additional step!
====

==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:../../README.adoc[Index]|link:../general.adoc[OverView]|link:../shortings.adoc[shortings]|link:../terms.adoc[agrirouter in a nutshell]
|====