= Videos
:imagesdir: ./../../assets/images/
:toc:
:toc-title:
:toclevels: 4

== vid:avi – AVI Video Files

=== Definition

This format is used to exchange an avi video file. It can forward the binary avi-Content, but currently no file name or other meta data.

=== Command

[cols=",",]
|==================
|Command |vid:avi
|Protobuf Schema |-
|TypeURL |“”
|==================

=== Format

The avi file has to be formatted to a Base64-encoding of its binary data. It must be sent as a string.

[NOTE]
====
The base64-encoding of the binary file is not the same as the base64 encoding of the message. It is an additional step!
====

== vid:wmv – WMV Video Files

=== Definition

This format is used to exchange an wmv video file. It can forward the binary wmv-Content, but currently no file name or other meta data.

=== Command

[cols=",",]
|==================
|Command |vid:wmv
|Protobuf Schema |-
|TypeURL |“”
|==================

=== Format

The wmv file has to be formatted to a Base64-encoding of its binary data. It must be sent as a string.

[NOTE]
====
The base64-encoding of the binary file is not the same as the base64 encoding of the message. It is an additional step!
====

== vid:mp4 – MPEG4 Video Files

=== Definition

This format is used to exchange an MPEG4 video file. It can forward the binary mp4-Content, but currently no file name or other meta data.

=== Command

[cols=",",]
|==================
|Command |vid:mp4
|Protobuf Schema |-
|TypeURL |“”
|==================

=== Format

The mp4 file has to be formatted to a Base64-encoding of its binary data. It must be sent as a string.

[NOTE]
====
The base64-encoding of the binary file is not the same as the base64 encoding of the message. It is an additional step!
====




==== Link Section
This page is found in every file and links to the major topics
[width="100%"]
|====
|link:../../README.adoc[Index]|link:../general.adoc[OverView]|link:../shortings.adoc[shortings]|link:../terms.adoc[agrirouter in a nutshell]
|====