= Videos
:imagesdir: ./../../assets/images/
*Table of Content*
:toc:
:toc-title:
:toclevels: 4

== vid:avi – AVI Video Files

=== Definition

This format is used to exchange an avi video file. It can forward the binary avi-Content, but currently no file name or other meta data.

=== Command

[cols=",",]
|==================
|Command |vid:avi
|Protobuf Schema |-
|TypeURL |“”
|==================

=== Format

The bmp file has to be formatted to a Base64-encoding of its binary data. It must be sent as a string.

== vid:wmv – WMV Video Files

=== Definition

This format is used to exchange an wmv video file. It can forward the binary wmv-Content, but currently no file name or other meta data.

=== Command

[cols=",",]
|==================
|Command |vid:wmv
|Protobuf Schema |-
|TypeURL |“”
|==================

=== Format

The bmp file has to be formatted to a Base64-encoding of its binary data. It must be sent as a string.

== vid:mp4 – MPEG4 Video Files

=== Definition

This format is used to exchange an MPEG4 video file. It can forward the binary mp4-Content, but currently no file name or other meta data.

=== Command

[cols=",",]
|==================
|Command |vid:mp4
|Protobuf Schema |-
|TypeURL |“”
|==================

=== Format

The bmp file has to be formatted to a Base64-encoding of its binary data. It must be sent as a string.